
const mt=document.getElementById('menuToggle');if(mt)mt.addEventListener('click',()=>{const a=document.getElementById('app');if(innerWidth<=980)a.classList.toggle('mobile-open');else a.classList.toggle('collapsed')});
function openModal(t,h){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').innerHTML=h;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
document.getElementById('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function toast(m){alert(m)}
function formReady(){return `<div class="form-grid"><div class="field"><label>ผลตรวจ</label><select><option>ผ่าน</option><option>ไม่ผ่าน</option></select></div><div class="field"><label>วันที่ตรวจ</label><input type="date"></div><div class="field full"><label>หมายเหตุ</label><textarea rows="3"></textarea></div></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึกเรียบร้อย');closeModal()">บันทึก</button></div>`}
function uploadForm(){return `<div class="field"><label>เลือกเอกสาร PDF/JPG</label><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png"></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('อัปโหลดสำเร็จ');closeModal()">อัปโหลด</button></div>`}
function confirmSend(f){return `<p>ยืนยันส่งแบบฟอร์ม ${f} เข้าสู่กระบวนการตรวจสอบหรือไม่</p><div class="notice">เมื่อส่งแล้ว หากต้องการแก้ไขต้องให้ผู้ตรวจส่งกลับ</div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-primary" onclick="toast('ส่ง ${f} แล้ว');closeModal()">ยืนยันส่ง</button></div>`}
function reviewForm(f){return `<div class="notice">ตรวจข้อมูลและเอกสาร ${f} ครบถ้วน 6/6 รายการ</div><div class="field"><label>Checklist</label><textarea rows="5">✓ ข้อมูลนักศึกษาถูกต้อง
✓ คุณสมบัติผ่านเกณฑ์
✓ เอกสารแนบครบ
✓ ลายมือชื่อครบ</textarea></div><div class="field"><label>ความเห็น</label><textarea rows="3"></textarea></div><div class="actions"><button class="btn btn-warn" onclick="toast('ส่งกลับแก้ไขแล้ว');closeModal()">ส่งกลับแก้ไข</button><button class="btn btn-success" onclick="toast('อนุมัติแล้ว');closeModal()">อนุมัติ</button></div>`}
function approveForm(f){return reviewForm(f)}
function companyConfirm(){return `<div class="form-grid"><div class="field"><label>ตำแหน่งงาน</label><input value="Software Developer Intern"></div><div class="field"><label>พี่เลี้ยง</label><input value="ศิริพร ใจดี"></div><div class="field"><label>วันที่เริ่ม</label><input type="date" value="2026-11-01"></div><div class="field"><label>วันที่สิ้นสุด</label><input type="date" value="2027-02-28"></div><div class="field full"><label>เงื่อนไข/หมายเหตุ</label><textarea rows="3"></textarea></div></div><div class="actions"><button class="btn btn-danger" onclick="toast('ปฏิเสธแล้ว');closeModal()">ไม่รับ</button><button class="btn btn-success" onclick="toast('ยืนยันรับนักศึกษาแล้ว');closeModal()">ยืนยันรับ</button></div>`}
function logbookForm(){return `<div class="form-grid"><div class="field"><label>สัปดาห์</label><input type="number" value="9"></div><div class="field"><label>ช่วงวันที่</label><input type="date"></div><div class="field full"><label>งานที่ดำเนินการ</label><textarea rows="4"></textarea></div><div class="field full"><label>ไฟล์แนบ</label><input type="file" multiple></div></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึก Logbook แล้ว');closeModal()">บันทึก</button></div>`}
function calendarForm(){return `<div class="form-grid"><div class="field"><label>นักศึกษา</label><select><option>กมลชนก วัฒนชัย</option></select></div><div class="field"><label>รูปแบบ</label><select><option>On-site</option><option>Online</option></select></div><div class="field"><label>วันที่</label><input type="date"></div><div class="field"><label>เวลา</label><input type="time"></div><div class="field"><label>ระยะเวลา (นาที)</label><input type="number" value="60"></div><div class="field"><label>Buffer (นาที)</label><input type="number" value="15"></div></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('สร้างนัดแล้ว');closeModal()">สร้างนัด</button></div>`}
function visitForm(){return `<div class="field"><label>ผลการนิเทศ</label><select><option>ดีมาก</option><option>ดี</option><option>ต้องปรับปรุง</option></select></div><div class="field"><label>รายละเอียด</label><textarea rows="5"></textarea></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึกผลนิเทศแล้ว');closeModal()">บันทึก</button></div>`}
function evaluationForm(who){return `<p>ผู้ประเมิน: <b>${who}</b></p><table><tr><th>หัวข้อ</th><th>คะแนนเต็ม</th><th>คะแนน</th></tr><tr><td>ความรู้และทักษะวิชาชีพ</td><td>30</td><td><input type="number" value="26" min="0" max="30"></td></tr><tr><td>ความรับผิดชอบและวินัย</td><td>25</td><td><input type="number" value="23"></td></tr><tr><td>การสื่อสารและทำงานเป็นทีม</td><td>25</td><td><input type="number" value="22"></td></tr><tr><td>ผลงาน/รายงาน</td><td>20</td><td><input type="number" value="17"></td></tr></table><div class="field"><label>ข้อเสนอแนะ</label><textarea rows="3"></textarea></div><div class="actions"><span></span><button class="btn btn-primary" onclick="toast('บันทึกผลประเมินแล้ว');closeModal()">บันทึกผล</button></div>`}
function closeProject(){return `<p>ยืนยันปิดโครงการสหกิจศึกษาของนักศึกษารายนี้?</p><div class="field"><label>หมายเหตุการปิดโครงการ</label><textarea rows="3"></textarea></div><div class="notice">ระบบจะบันทึกผู้ดำเนินการ วันเวลา ผลคะแนน และเอกสารทั้งหมดใน Audit Log</div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-success" onclick="toast('ปิดโครงการแล้ว');closeModal()">ยืนยันปิดโครงการ</button></div>`}

function roundForm(){return `<div class="form-grid"><div class="field"><label>ปีการศึกษา</label><select><option>2569</option></select></div><div class="field"><label>ภาคการศึกษา</label><select><option>1</option></select></div><div class="field"><label>เปิดรับสมัคร</label><input type="date" value="2026-08-01"></div><div class="field"><label>ปิดรับสมัคร</label><input type="date" value="2026-08-31"></div><div class="field"><label>เริ่มปฏิบัติงาน</label><input type="date" value="2026-11-01"></div><div class="field"><label>สิ้นสุดปฏิบัติงาน</label><input type="date" value="2027-02-28"></div></div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-primary" onclick="toast('บันทึกรอบสหกิจศึกษาแล้ว');closeModal()">บันทึก</button></div>`}
function companyForm(){return `<div class="form-grid"><div class="field"><label>ชื่อสถานประกอบการ</label><input value="บริษัท ดิจิทัล โซลูชัน จำกัด"></div><div class="field"><label>ผู้ประสานงาน</label><input value="ศิริพร ใจดี"></div><div class="field"><label>โทรศัพท์</label><input value="02-555-0188"></div><div class="field"><label>อีเมล</label><input value="hr@digitalsolution.co.th"></div><div class="field full"><label>ที่อยู่/สถานที่ปฏิบัติงาน</label><textarea rows="3">กรุงเทพมหานคร</textarea></div></div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-primary" onclick="toast('บันทึกสถานประกอบการแล้ว');closeModal()">บันทึก</button></div>`}
function positionForm(){return `<div class="form-grid"><div class="field"><label>ตำแหน่ง</label><input value="Software Developer Intern"></div><div class="field"><label>จำนวนที่ประกาศรับ</label><input type="number" value="2" min="1"></div><div class="field"><label>สาขา/หลักสูตรที่ต้องการ</label><input value="วิศวกรรมคอมพิวเตอร์, เทคโนโลยีสารสนเทศ"></div><div class="field"><label>GPA ขั้นต่ำ</label><input type="number" step="0.01" value="2.50"></div><div class="field full"><label>ทักษะที่ต้องการ</label><textarea rows="3">Python, JavaScript, SQL, Git</textarea></div><div class="field full"><label>คุณสมบัติเพิ่มเติม</label><textarea rows="3">สื่อสารและทำงานเป็นทีมได้ดี พร้อมเรียนรู้เทคโนโลยีใหม่</textarea></div><div class="field full"><label>รายละเอียดงาน</label><textarea rows="3">พัฒนาและทดสอบระบบ Web Application</textarea></div></div><div class="notice">จำนวนที่ประกาศรับเป็นค่าตั้งต้น สถานประกอบการสามารถยืนยันรับเพิ่มภายหลังได้ โดยระบบเก็บจำนวนเดิม จำนวนรับจริง เหตุผล และผู้ดำเนินการไว้ในประวัติ</div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-primary" onclick="toast('บันทึกตำแหน่งและคุณสมบัติแล้ว');closeModal()">บันทึก</button></div>`}
function interviewForm(){return `<div class="form-grid"><div class="field"><label>นักศึกษา</label><select><option>กมลชนก วัฒนชัย</option></select></div><div class="field"><label>ตำแหน่ง</label><select><option>Software Developer Intern</option></select></div><div class="field"><label>วันสัมภาษณ์</label><input type="date" value="2026-09-05"></div><div class="field"><label>เวลา</label><input type="time" value="10:00"></div><div class="field"><label>รูปแบบ</label><select><option>Online</option><option>On-site</option></select></div><div class="field"><label>ผู้สัมภาษณ์</label><input value="HR + Technical Lead"></div><div class="field full"><label>ลิงก์/สถานที่</label><input value="Microsoft Teams"></div></div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-primary" onclick="toast('บันทึกนัดสัมภาษณ์แล้ว');closeModal()">บันทึกนัด</button></div>`}
function interviewResultForm(){return `<div class="form-grid"><div class="field"><label>ผลสัมภาษณ์</label><select><option>ผ่าน</option><option>สำรอง</option><option>ไม่ผ่าน</option></select></div><div class="field"><label>คะแนน</label><input type="number" value="88" min="0" max="100"></div><div class="field full"><label>ความเห็นสถานประกอบการ</label><textarea rows="3">ทักษะตรงตามตำแหน่ง สื่อสารดี พร้อมรับเข้าปฏิบัติงาน</textarea></div></div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-success" onclick="toast('บันทึกผลสัมภาษณ์แล้ว');closeModal()">บันทึกผล</button></div>`}
function overQuotaForm(){return `<div class="notice"><b>จำนวนรับเกินที่ประกาศ</b><br>ประกาศรับ 2 คน · ยืนยันแล้ว 2 คน · รายการนี้จะเป็นคนที่ 3</div><div class="field"><label>เหตุผลการรับเพิ่ม</label><textarea rows="3">ผลสัมภาษณ์ผ่านเกณฑ์และสถานประกอบการมีโครงการเพิ่มเติม</textarea></div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-success" onclick="toast('ยืนยันรับเพิ่มแล้ว และบันทึก Audit Trail');closeModal()">ยืนยันรับเพิ่ม</button></div>`}
function approvalForm(){return `<div class="notice">ลำดับอนุมัติ: อาจารย์ที่ปรึกษา → ผู้รับผิดชอบสหกิจ/หลักสูตร → ผู้มีอำนาจอนุมัติ</div><div class="field"><label>ความเห็น</label><textarea rows="3"></textarea></div><div class="actions"><button class="btn btn-warn" onclick="toast('ส่งกลับแก้ไขแล้ว');closeModal()">ส่งกลับ</button><button class="btn btn-danger" onclick="toast('ไม่อนุมัติแล้ว');closeModal()">ไม่อนุมัติ</button><button class="btn btn-success" onclick="toast('อนุมัติขั้นนี้แล้ว');closeModal()">อนุมัติ</button></div>`}
function historyModal(){return `<div class="timeline"><p><b>01 ส.ค. 2569</b> เปิดรอบสหกิจศึกษา</p><p><b>12 ส.ค. 2569</b> นักศึกษายื่นใบสมัคร</p><p><b>20 ส.ค. 2569</b> ผ่านการตรวจคุณสมบัติ</p><p><b>05 ก.ย. 2569</b> สัมภาษณ์กับสถานประกอบการ</p><p><b>06 ก.ย. 2569</b> ผลสัมภาษณ์: ผ่าน</p><p><b>08 ก.ย. 2569</b> จับคู่ตำแหน่ง Software Developer Intern</p><p><b>12 ก.ย. 2569</b> อนุมัติออกสหกิจครบทุกลำดับ</p><p><b>01 พ.ย. 2569</b> เริ่มปฏิบัติงาน</p></div>`}

/* SYSTEM 7 v201 prototype behavior */
function rusToggleAdvanced(btn){
  const root=btn.closest('.s7-filter'); if(!root) return;
  const panel=root.querySelector('.s7-filter-more'); if(!panel) return;
  const hidden=panel.classList.toggle('s7-hidden');
  btn.classList.toggle('open',!hidden);
  btn.innerHTML=(hidden?'ตัวกรองเพิ่มเติม':'ซ่อนตัวกรองเพิ่มเติม')+' <span class="chev">▾</span>';
}
function rusResetFilter(btn){
  const root=btn.closest('.s7-filter')||btn.closest('.card-b')||document;
  root.querySelectorAll('input').forEach(el=>{if(['text','search','date'].includes((el.type||'text').toLowerCase())) el.value='';});
  root.querySelectorAll('select').forEach(el=>el.selectedIndex=0);
  const scope=root.closest('.card-b')||root.closest('main')||document;
  scope.querySelectorAll('table tr').forEach(tr=>tr.style.display='');
  toast('ล้างตัวกรองแล้ว');
}
function rusApplyFilter(btn){
  const root=btn.closest('.s7-filter')||btn.closest('.toolbar')||btn.closest('.filter-grid')||btn.closest('.card-b')||document;
  const scope=root.closest('.card-b')||root.closest('main')||document;
  const qInputs=[...root.querySelectorAll('input[type="text"],input:not([type])')];
  const qs=qInputs.map(x=>x.value.trim().toLowerCase()).filter(Boolean);
  const vals=[...root.querySelectorAll('select')].map(s=>s.value.trim().toLowerCase()).filter(Boolean);
  let shown=0,total=0;
  scope.querySelectorAll('table tr').forEach(tr=>{
    if(tr.querySelector('th')) return;
    total++;
    const hay=((tr.dataset.filter||'')+' '+tr.innerText).toLowerCase();
    const ok=qs.every(q=>hay.includes(q)) && vals.every(v=>hay.includes(v));
    tr.style.display=ok?'':'none'; if(ok) shown++;
  });
  toast('แสดงผล '+shown+' จาก '+total+' รายการ');
}
function candidateDetail(name='กมลชนก วัฒนชัย'){
 return `<div class="detail-tabs"><button class="active">สรุปคุณสมบัติ</button><button onclick="this.parentElement.querySelector('.active').classList.remove('active');this.classList.add('active');document.getElementById('cDetail').innerHTML='<p><b>เอกสารครบ 6/6 รายการ</b></p><p>Transcript · Resume · Portfolio · หนังสือยินยอม · หลักฐานกิจกรรม · เอกสารประกอบอื่น</p>'">เอกสาร</button><button onclick="this.parentElement.querySelector('.active').classList.remove('active');this.classList.add('active');document.getElementById('cDetail').innerHTML=historyModal()">ประวัติ</button></div><div id="cDetail"><p><b>${name}</b></p><table><tr><th>เงื่อนไข</th><th>Requirement</th><th>ข้อมูลนักศึกษา</th><th>ผล</th></tr><tr><td>หลักสูตร</td><td>วิศวกรรมคอมพิวเตอร์/IT</td><td>วิศวกรรมคอมพิวเตอร์</td><td><span class="pill ok">ผ่าน</span></td></tr><tr><td>GPAX</td><td>≥ 2.50</td><td>3.05</td><td><span class="pill ok">ผ่าน</span></td></tr><tr><td>ทักษะ</td><td>Python, JavaScript, SQL, Git</td><td>ตรง 4/4</td><td><span class="pill ok">ผ่าน</span></td></tr></table></div>`;
}
function confirmSelection(name='กมลชนก วัฒนชัย'){
 return `<p>ยืนยันให้ <b>${name}</b> ผ่านการตรวจคุณสมบัติและส่งเข้าคิวสัมภาษณ์หรือไม่</p><div class="field"><label>หมายเหตุ</label><textarea rows="3">คุณสมบัติตรงตาม Requirement ของตำแหน่ง</textarea></div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-success" onclick="toast('ส่งเข้าคิวสัมภาษณ์แล้ว');closeModal()">ยืนยันและส่งสัมภาษณ์</button></div>`;
}
function interviewDetail(name='กมลชนก วัฒนชัย'){
 return `<div class="detail-tabs"><button class="active">ข้อมูลนัด</button><button onclick="this.parentElement.querySelector('.active').classList.remove('active');this.classList.add('active');document.getElementById('iDetail').innerHTML='<p><b>ผลสัมภาษณ์</b></p><p>ยังไม่บันทึกผล</p>'">ผลสัมภาษณ์</button><button onclick="this.parentElement.querySelector('.active').classList.remove('active');this.classList.add('active');document.getElementById('iDetail').innerHTML=historyModal()">ประวัติ</button></div><div id="iDetail"><p><b>${name}</b> · Software Developer Intern</p><p>5 ก.ย. 2569 เวลา 10:00 · Online · Microsoft Teams</p><p>ผู้สัมภาษณ์: HR + Technical Lead</p></div>`;
}
function matchingDetail(name='กมลชนก วัฒนชัย'){
 return `<div class="detail-tabs"><button class="active">ผลสัมภาษณ์</button><button onclick="this.parentElement.querySelector('.active').classList.remove('active');this.classList.add('active');document.getElementById('mDetail').innerHTML='<p><b>ตำแหน่ง</b> Software Developer Intern</p><p>ประกาศรับ 2 คน · ยืนยันแล้ว 2 คน · หากยืนยันรายนี้จะเป็น 3 คน</p>'">ข้อมูลตำแหน่ง</button><button onclick="this.parentElement.querySelector('.active').classList.remove('active');this.classList.add('active');document.getElementById('mDetail').innerHTML=historyModal()">ประวัติ</button></div><div id="mDetail"><p><b>${name}</b></p><p>ผล: <span class="pill ok">ผ่าน</span> · คะแนน 88/100</p><p>ความเห็น: ทักษะตรงตามตำแหน่ง สื่อสารดี พร้อมรับเข้าปฏิบัติงาน</p></div>`;
}
function confirmNormalMatch(name='ณัฐวุฒิ สุขใจ'){
 return `<p>ยืนยันการจับคู่ <b>${name}</b> กับตำแหน่ง Software Developer Intern หรือไม่</p><div class="notice">จำนวนรับยังไม่เกินจำนวนที่ประกาศ ระบบจะบันทึกผลการจับคู่และส่งต่อ STEP 5 เพื่อพิจารณาอนุมัติออกสหกิจ</div><div class="actions"><button class="btn btn-secondary" onclick="closeModal()">ยกเลิก</button><button class="btn btn-success" onclick="toast('ยืนยันการจับคู่แล้ว');closeModal()">ยืนยันจับคู่</button></div>`;
}
